import ExchangeComposer from './ExchangeComposer';
import { useRef, useState, useEffect } from 'react';
import { useSearchParams } from 'react-router';
import { OshiIcon } from '../../components/common/OshiIcon';
import { generateId } from '../../services/id';
import { loadEvents } from '../../services/storage';
import { loadShopping } from '../../services/shopping';
import { shoppingForEvent } from '../../services/shoppingMemos';
import { exchangeKinds, exchangeStages, exchangeSteps, exchangeError, loadExchanges, saveExchanges, type ExchangeRecord } from '../../services/exchanges';
const fresh=():ExchangeRecord=>({id:generateId(),kind:'exchange',stage:'negotiating',partner:'',contact:'',eventId:'',outgoing:[{name:'',quantity:1}],incoming:[{name:'',quantity:1}],method:'mail',money:'none',amount:'',deadline:'',time:'',place:'',tracking:'',memo:'',done:{},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
export default function ExchangePage(){
  const [params,setParams]=useSearchParams();
  const [view,setView]=useState(params.has('edit')?'records':'compose');
  const [initial]=useState(()=>{try{return {records:loadExchanges(),error:''};}catch{return {records:[] as ExchangeRecord[],error:'取引データを読み込めませんでした。データを保護するため編集を停止しています。'};}});
  const [records,setRecords]=useState(initial.records),[filter,setFilter]=useState('open'),[kind,setKind]=useState(''),[query,setQuery]=useState(''),[message,setMessage]=useState('');
  const [newRecord,setNewRecord]=useState<ExchangeRecord | undefined>(()=>fresh());
  const editing=params.get('edit');
  const selected=editing==='new'?newRecord:records.find(r=>r.id===editing);
  const events=loadEvents();
  function close(){setParams({});setNewRecord(undefined);}
  function persist(next:ExchangeRecord[]){try{saveExchanges(next);setRecords(next);return true;}catch{setMessage('保存できませんでした。入力内容は残しています。端末の保存容量などを確認してください。');return false;}}
  const visible=records.filter(r=>(!kind||r.kind===kind)&&(filter==='all'||(filter==='open'?r.stage==='active'||r.stage==='negotiating'||r.stage==='recruiting':r.stage===filter))&&`${r.partner} ${r.contact} ${[...r.outgoing,...r.incoming].map(i=>i.name).join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999')||b.updatedAt.localeCompare(a.updatedAt));
  return <main className="exchange-page"><header className="page-header"><div><h1 className="icon-heading"><OshiIcon name="exchange" size={30}/>交換・譲渡</h1><p>募集からDMまでの文章作成と、自分のお取引を管理します。</p></div></header>
    <div className="exchange-template-tabs"><button type="button" aria-pressed={view==='compose'} onClick={()=>{close();setView('compose');}}>文章を作る</button><button type="button" aria-pressed={view==='records'} onClick={()=>setView('records')}>お取引の記録</button></div>
    {view==='compose'?<ExchangeComposer/>:initial.error?<p role="alert">{initial.error}</p>:<>
    {!editing&&<button type="button" className="exchange-add" onClick={()=>{setNewRecord(fresh());setParams({edit:'new'});setMessage('');}}>＋ お取引を登録</button>}
    <p role="status">{message}</p>
    {editing&&(selected?<ExchangeEditor key={selected.id} record={selected} onCancel={close} onSave={record=>{if(persist(records.some(r=>r.id===record.id)?records.map(r=>r.id===record.id?record:r):[...records,record])){close();setMessage('お取引を保存しました。');}}} onDelete={()=>{if(window.confirm('このお取引を削除しますか？')&&persist(records.filter(r=>r.id!==selected.id))){close();setMessage('削除しました。');}}}/>:<p>取引が見つかりません。<button type="button" onClick={close}>一覧へ戻る</button></p>)}
    {!editing&&<><section className="shopping-panel exchange-filters" aria-label="取引の絞り込み"><label className="form-field">検索<input type="search" placeholder="相手・商品名" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="exchange-two"><label className="form-field">状況<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">未完了</option><option value="completed">完了</option><option value="cancelled">中止</option><option value="all">すべて</option></select></label><label className="form-field">取引の種類<select value={kind} onChange={e=>setKind(e.target.value)}><option value="">すべて</option>{Object.entries(exchangeKinds).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label></div></section>
    <p>{visible.length}件のお取引</p><div className="exchange-list">{visible.map(record=>{const steps=exchangeSteps(record),next=steps.find(s=>!record.done[s.id]);return <article className="shopping-panel" key={record.id}><div className="exchange-card-heading"><span className="task-tag">{exchangeKinds[record.kind]}</span><span>{exchangeStages[record.stage]}</span></div><h2>{record.partner}さん</h2>{record.eventId&&<p className="shopping-note">{events.find(e=>e.id===record.eventId)?.title||'関連イベント'}</p>}{record.kind!=='receive'&&<p>渡す：{record.outgoing.map(i=>`${i.name} ×${i.quantity}`).join('、')}</p>}{record.kind!=='give'&&<p>受け取る：{record.incoming.map(i=>`${i.name} ×${i.quantity}`).join('、')}</p>}<p className="shopping-note">{record.method==='mail'?'郵送':'手渡し'}{record.deadline&&` ／ ${record.deadline.replaceAll('-','/')} ${record.time}`}</p>{record.stage==='active'&&record.kind!=='receive'&&record.done.send&&!record.done.delivered&&<p>相手の受取連絡待ち</p>}{record.stage==='active'&&<p>{next?`次に確認：${next.label}`:'確認済みです。取引を開いて完了にできます。'}</p>}<button type="button" onClick={()=>{setParams({edit:record.id});setMessage('');}}>確認・編集</button></article>;})}</div>{!visible.length&&<p>{records.length?'条件に合う取引はありません。':'まだお取引はありません。「お取引を登録」から追加できます。'}</p>}</>}
    </>}
  </main>;
}
function ExchangeEditor({record,onSave,onCancel,onDelete}:{record:ExchangeRecord;onSave:(r:ExchangeRecord)=>void;onCancel:()=>void;onDelete:()=>void}){
  const [draft,setDraft]=useState(record),[error,setError]=useState('');const ref=useRef<HTMLFormElement>(null);
  useEffect(()=>{ref.current?.scrollIntoView({block:'start'});},[]);
  const patch=(value:Partial<ExchangeRecord>)=>setDraft(old=>({...old,...value}));
  const events=loadEvents();let products:{id:string;name:string;variant:string}[]=[];
  try{if(draft.eventId)products=shoppingForEvent(draft.eventId,events).flatMap(m=>loadShopping(m.id).products);}catch{/* Manual entry remains available. */}
  const steps=exchangeSteps(draft);
  function items(field:'outgoing'|'incoming',label:string){return <section className="exchange-section"><h3>{label}</h3>{draft[field].map((item,index)=><div className="exchange-item" key={index}><label className="form-field">商品名・種類<input required list="exchange-products" value={item.name} onChange={e=>patch({[field]:draft[field].map((v,i)=>i===index?{...v,name:e.target.value}:v)})} placeholder="例：アクスタ・キャラクター名"/></label><label className="form-field">個数<input type="number" inputMode="numeric" min="1" step="1" required value={Number.isFinite(item.quantity)?item.quantity:""} onChange={e=>patch({[field]:draft[field].map((v,i)=>i===index?{...v,quantity:e.target.valueAsNumber}:v)})}/></label>{draft[field].length>1&&<button className="secondary-button" type="button" aria-label={`${label}の商品${index+1}を削除`} onClick={()=>patch({[field]:draft[field].filter((_,i)=>i!==index)})}>削除</button>}</div>)}<button type="button" className="secondary-button" onClick={()=>patch({[field]:[...draft[field],{name:'',quantity:1}]})}>＋ 商品を追加</button></section>;}
  return <form ref={ref} className="shopping-panel exchange-editor" onSubmit={e=>{e.preventDefault();const problem=exchangeError(draft);if(problem){setError(problem);return;}onSave({...draft,partner:draft.partner.trim(),updatedAt:new Date().toISOString()});}}>
    <h2>お取引を記録</h2><div className="exchange-two"><label className="form-field">種類<select value={draft.kind} onChange={e=>{const kind=e.target.value as ExchangeRecord['kind'];patch({kind,money:kind==='give'?'receive':kind==='receive'?'pay':'none',done:{},stage:'negotiating'});}}>{Object.entries(exchangeKinds).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="form-field">状況<select value={draft.stage} onChange={e=>patch({stage:e.target.value as ExchangeRecord['stage']})}>{Object.entries(exchangeStages).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div>
    <label className="form-field">相手の名前・ニックネーム<input required value={draft.partner} onChange={e=>patch({partner:e.target.value})}/></label><label className="form-field">連絡先・アカウント（任意）<input value={draft.contact} onChange={e=>patch({contact:e.target.value})} placeholder="例：Xのアカウント名"/></label>
    <label className="form-field">関連イベント（任意）<select value={draft.eventId} onChange={e=>patch({eventId:e.target.value})}><option value="">なし</option>{draft.eventId&&!events.some(e=>e.id===draft.eventId)&&<option value={draft.eventId}>削除済みのイベント</option>}{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><datalist id="exchange-products">{products.map(p=><option key={p.id} value={`${p.name}${p.variant?' '+p.variant:''}`}/>)}</datalist>
    {draft.kind!=='receive'&&items('outgoing','自分が渡すグッズ')}{draft.kind!=='give'&&items('incoming','自分が受け取るグッズ')}
    <section className="exchange-section"><h3>受け渡し</h3><label className="form-field">方法<select value={draft.method} onChange={e=>patch({method:e.target.value as ExchangeRecord['method'],time:''})}><option value="mail">郵送</option><option value="hand">手渡し</option></select></label><div className="exchange-two"><label className="form-field">{draft.method==='mail'?'対応予定日（任意）':'待ち合わせ日（任意）'}<input type="date" value={draft.deadline} onChange={e=>patch({deadline:e.target.value})}/></label>{draft.method==='hand'&&<label className="form-field">時刻（任意）<input type="time" value={draft.time} onChange={e=>patch({time:e.target.value})}/></label>}</div>{draft.method==='hand'?<label className="form-field">待ち合わせ場所<input value={draft.place} onChange={e=>patch({place:e.target.value})}/></label>:<label className="form-field">発送方法・追跡番号（任意）<input value={draft.tracking} onChange={e=>patch({tracking:e.target.value})}/></label>}</section>
    <section className="exchange-section"><h3>代金・差額</h3><label className="form-field">お金のやり取り<select value={draft.money} onChange={e=>patch({money:e.target.value as ExchangeRecord['money'],done:{...draft.done,money:false}})}><option value="none">なし</option><option value="pay">自分が支払う</option><option value="receive">自分が受け取る</option></select></label>{draft.money!=='none'&&<label className="form-field">金額（円・未定なら空欄）<input type="number" className="money-input" inputMode="numeric" min="0" step="1" value={draft.amount} onChange={e=>patch({amount:e.target.value})}/></label>}</section>
    <section className="exchange-section"><h3>進み具合の確認</h3>{steps.map(step=><label className="ticket-check" key={step.id}><input type="checkbox" checked={!!draft.done[step.id]} onChange={e=>patch({done:{...draft.done,[step.id]:e.target.checked},...(draft.stage==='completed'&&!e.target.checked?{stage:'active' as const}:{})})}/>{step.label.replace('する','した').replace('支払う','支払った').replace('受け取る','受け取った').replace('手渡す','手渡した')}</label>)}{steps.every(s=>draft.done[s.id])&&draft.stage!=='completed'&&<button type="button" onClick={()=>patch({stage:'completed'})}>取引を完了にする</button>}</section>
    <label className="form-field">メモ<textarea rows={3} value={draft.memo} onChange={e=>patch({memo:e.target.value})}/></label>{error&&<p role="alert">{error}</p>}<div className="exchange-two"><button className="secondary-button" type="button" onClick={onCancel}>キャンセル</button><button type="submit">保存</button></div><button className="secondary-button" type="button" onClick={onDelete}>この取引を削除</button>
  </form>;
}
