import { useState } from 'react';
import { loadCalendar,saveCalendar,textOnColor,type CalendarSettings } from '../../services/calendar';
import { generateId } from '../../services/id';
const palette=['#e8b9c8','#edc4ad','#efce87','#bbd8b5','#a9d9d4','#b6cbe9','#c8bee3','#c9c4be'];
function color(h:number,s:number,l:number){s/=100;l/=100;const a=s*Math.min(l,1-l);return '#'+[0,8,4].map(n=>{const k=(n+h/30)%12;return Math.round(255*(l-a*Math.max(-1,Math.min(k-3,9-k,1)))).toString(16).padStart(2,'0');}).join('');}
function hsl(hex:string){const [r,g,b]=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255),max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,l=(max+min)/2;return [d?((max===r?(g-b)/d+(g<b?6:0):max===g?(b-r)/d+2:(r-g)/d+4)*60):0,d?d/(1-Math.abs(2*l-1))*100:0,l*100];}
function ColorPicker({value,onChange}:{value:string;onChange:(s:string)=>void}){
 const [h,s,l]=hsl(value);
 const set=(hue=h,saturation=s,lightness=l)=>onChange(color(hue,saturation,lightness));
 return <div className="calendar-color-picker"><div className="calendar-palette">{palette.map(c=><button type="button" key={c} style={{background:c}} aria-label={`色 ${c}`} aria-pressed={value===c} onClick={()=>onChange(c)}/>)}</div><details><summary>自由に選ぶ</summary><div className="calendar-color-wheel" role="slider" tabIndex={0} aria-label="色相" aria-valuemin={0} aria-valuemax={359} aria-valuenow={Math.round(h)%360} onKeyDown={e=>{if(['ArrowRight','ArrowUp','ArrowLeft','ArrowDown','Home','End'].includes(e.key)){e.preventDefault();set(e.key==='Home'?0:e.key==='End'?359:(h+(['ArrowRight','ArrowUp'].includes(e.key)?5:355))%360,s||60,l===0||l===100?75:l);}}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect();set((Math.atan2(e.clientY-r.top-r.height/2,e.clientX-r.left-r.width/2)*180/Math.PI+450)%360,s||60,l===0||l===100?75:l);}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId)){const r=e.currentTarget.getBoundingClientRect();set((Math.atan2(e.clientY-r.top-r.height/2,e.clientX-r.left-r.width/2)*180/Math.PI+450)%360,s||60,l===0||l===100?75:l);}}}><span style={{background:value,color:textOnColor(value)}}>{Math.round(h)}°</span></div><label className="form-field">鮮やかさ<input type="range" min="0" max="100" value={Math.round(s)} onChange={e=>set(h,Number(e.target.value),l)}/></label><label className="form-field">明るさ<input type="range" min="0" max="100" value={Math.round(l)} onChange={e=>set(h,s,Number(e.target.value))}/></label></details></div>;
}
export default function CalendarSettingsPage(){
 const [initial]=useState(()=>{try{return {data:loadCalendar(),error:''};}catch{return {data:null,error:'カレンダー設定を読み込めませんでした。'};}});
 const [draft,setDraft]=useState<CalendarSettings|null>(initial.data),[message,setMessage]=useState(initial.error);
 if(!draft)return <main><h1>カレンダー設定</h1><p role="alert">{message}</p></main>;
 return <main className="calendar-settings"><header className="page-header"><h1>カレンダーの色・文字</h1><p>自分だけの色分けと説明を設定できます。</p></header><form onSubmit={e=>{e.preventDefault();if(draft.labels.some(l=>!l.name.trim())){setMessage('ラベル名を入力してください。');return;}try{saveCalendar(draft);setMessage('保存しました。');}catch{setMessage('保存できませんでした。入力内容は残っています。');}}}>
  <label className="form-field form-field-full">カレンダー内の文字の太さ<select value={draft.weight} onChange={e=>setDraft({...draft,weight:Number(e.target.value) as CalendarSettings['weight']})}><option value={400}>標準</option><option value={500}>中太</option><option value={700}>太字</option></select></label>
  <p className="form-field-full" style={{fontWeight:draft.weight}}>プレビュー：28日　イベント・参加予定</p>
  {draft.labels.map((label,index)=>{const update=(patch:Partial<typeof label>)=>setDraft({...draft,labels:draft.labels.map((v,i)=>i===index?{...v,...patch}:v)});return <section className="calendar-label-editor form-field-full" key={label.id}><label className="form-field">ラベル名<input required maxLength={40} value={label.name} onChange={e=>update({name:e.target.value})}/></label><label className="form-field">色の説明<input value={label.description} onChange={e=>update({description:e.target.value})} placeholder="例：うたプリの予定"/></label><ColorPicker value={label.color} onChange={color=>update({color})}/><span className="calendar-badge" style={{background:label.color,color:textOnColor(label.color),fontWeight:draft.weight}}>{label.name||'ラベルのプレビュー'}</span><p>{label.description}</p><button type="button" className="secondary-button" onClick={()=>{if(window.confirm(`「${label.name||'このラベル'}」を削除しますか？予定自体は残ります。`))setDraft({...draft,labels:draft.labels.filter(l=>l.id!==label.id),assignments:Object.fromEntries(Object.entries(draft.assignments).filter(([,v])=>v!==label.id))});}}>ラベルを削除</button></section>;})}
  <button type="button" className="secondary-button form-field-full" onClick={()=>setDraft({...draft,labels:[...draft.labels,{id:generateId(),name:'',description:'',color:palette[0]}]})}>＋ 色ラベルを追加</button><p className="form-field-full" role="status">{message}</p><button className="form-field-full" type="submit">設定を保存</button>
 </form></main>;
}
