import { extraModules, fieldsForTags, type GenreField } from "../../services/eventGenres";
export function DetailField({field,value,onChange}: {field:GenreField;value:string;onChange:(value:string)=>void}) {
  return <label className="form-field"><span>{field.label}</span>{field.options ? <select value={value} onChange={e=>onChange(e.target.value)}><option value="">未定・未入力</option>{field.options.map(option=><option key={option}>{option}</option>)}</select> : field.type === "textarea" ? <textarea rows={4} value={value} onChange={e=>onChange(e.target.value)}/> : <input type={field.type ?? "text"} min={field.type === "number" ? 0 : undefined} value={value} onChange={e=>onChange(e.target.value)}/>}</label>;
}
export default function GenreFields({tags,details,onChange}: {tags:string[];details:Record<string,string>;onChange:(value:Record<string,string>)=>void}) {
  return <div className="genre-fields form-field-full">{details.openingHours && <DetailField field={{key:"openingHours",label:"営業時間の補足（以前の入力）"}} value={details.openingHours} onChange={value=>onChange({...details,openingHours:value})}/>}{fieldsForTags(tags).filter(field=>field.key !== "entryMethod").map(field=><DetailField key={field.key} field={field} value={details[field.key] ?? ""} onChange={value=>onChange({...details,[field.key]:value})}/>)}</div>;
}
export function ExtraModules({tags,value,onChange,lottery}: {tags:string[];value:Record<string,Record<string,string>>;onChange:(value:Record<string,Record<string,string>>)=>void;lottery:boolean}) {
  return <section className="form-field-full genre-modules"><h3>追加する機能</h3>{Object.entries(extraModules).filter(([key,module])=>value[key] || module.tags.some(tag=>tags.includes(tag))).map(([key,module])=><section className="ticket-options" key={key}>{value[key] ? <><h4>{module.label}</h4><div className="genre-fields">{module.fields.filter(field=>key !== "order" || lottery || !field.key.startsWith("result")).map(field=><DetailField key={field.key} field={field} value={value[key][field.key] ?? ""} onChange={text=>onChange({...value,[key]:{...value[key],[field.key]:text}})}/>)}</div></> : <button type="button" className="secondary-button" onClick={()=>onChange({...value,[key]:{}})}>＋ {module.label}を追加</button>}</section>)}</section>;
}
